name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código com histórico completo para podermos fazer commits
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      # 2. Instalação do Emscripten
      - name: Setup Emscripten
        run: |
          sudo apt-get update
          sudo apt-get install -y emscripten

      # 3. Compilação da aplicação com o Makefile
      - name: Build with Makefile
        run: make

      # 4. Preparar os arquivos de deploy copiando os arquivos necessários para uma pasta de distribuição
      - name: Prepare deploy folder
        run: |
          mkdir -p deploy
          cp nex.html nex.js nex.wasm nex.css nex_wasm.js deploy/

      # 5. Deploy para a branch gh-pages usando a ação especializada
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
